cache: bundler
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-2.2.3
env:
  - CC=clang
  - CXX=clang++
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 1.9.2
    - rvm: 1.8.7
notifications:
  recipients:
    - cowboyd@thefrontside.net
before_install:
  - gem update --system 2.1.11
script:
  - bundle exec rake compile
  - bundle exec rspec spec/c
